### ISSUE TITLE
Program does not function with latest 1.0.3 release of binmerge

### ISSUE THREAD

**Issue by z3row0rm** [j68k/verifydump#24]
Thank you very much for creating this tool! Just tried to use this for the first time, and was having the following output when trying to verify some .chd games. I rolled back to the most current version of binmerge when this script was released and that fixed the issue. (binmerge 1.0.1). The game it failed on was the first one processed, Ace Combat 2 for Playstation.

Datfile loaded successfully with 10783 games
Traceback (most recent call last):
  File "exeentry.py", line 5, in <module>
  File "verifydump\console.py", line 45, in verifydump_main
  File "verifydump\verify.py", line 255, in verify_dumps
  File "verifydump\verify.py", line 240, in verify_dump_if_format_is_supported
  File "verifydump\verify.py", line 39, in verify_chd
  File "verifydump\convert.py", line 30, in convert_chd_to_normalized_redump_dump_folder
  File "verifydump\convert.py", line 63, in normalize_redump_bincue_dump
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\XXXXXXXXXXXXXXX\Ace Combat 2 (Track 1).bin' -> 'C:\\XXXXXXXXXXXXXXX\Ace Combat 2.bin'
[15884] Failed to execute script 'exeentry' due to unhandled exception!

**Comment by L4R5** [comment]
It also does not work with binmerge 1.0.2

**Comment by c0d3h4x0r** [comment]
The problem isn't with binmerge. The problem is with square brackets in the folder/file names. I've already posted a PR to fix this: https://github.com/j68k/verifydump/pull/26

**Comment by comradesean** [comment]
Is this due to folders/files of the host machine or in the dat file? I don't have any square brackets and I'm getting the same error 

```
verifydump.exe "Sony - PlayStation 2 - Datfile (11538) (2024-10-31 19-26-03).zip" "F:\ROMS\SONY PLAYSTATION 2"
Datfile loaded successfully with 11538 games
Traceback (most recent call last):
  File "exeentry.py", line 5, in <module>
  File "verifydump\console.py", line 45, in verifydump_main
  File "verifydump\verify.py", line 255, in verify_dumps
  File "verifydump\verify.py", line 240, in verify_dump_if_format_is_supported
  File "verifydump\verify.py", line 39, in verify_chd
  File "verifydump\convert.py", line 29, in convert_chd_to_normalized_redump_dump_folder
  File "verifydump\convert.py", line 39, in convert_chd_to_bincue
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1435, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[29868] Failed to execute script 'exeentry' due to unhandled exception!
```

**Comment by j68k** [comment]
This is fixed in verifydump 1.0.1 which was just released. (Sorry for the extremely slow response!)
